### ISSUE TITLE
Issues with Beta7 - Display resolution is not detected proper

### ISSUE THREAD

**Issue by tubalainen** [SvenVD/rpisurv#125]
Hi Sven.

Raspberry pi 3 b+
Raspberry OS Lite

Connected to a Philips full-HD TV via HDMI

Method of install
```
added gpu_mem=512 to /boot/config.txt
sudo apt get update ; sudo apt get upgrade
sudo apt get install git
git clone https://github.com/SvenVD/rpisurv
cd rpisurv
git checkout v3_latest
sudo ./install.sh
reboot
```

error from /var/syslog:
```
Aug 12 15:37:07 rpisurv systemd[1]: Created slice User Slice of UID 1000.
Aug 12 15:37:07 rpisurv systemd[1]: Starting User Runtime Directory /run/user/1000...
Aug 12 15:37:07 rpisurv systemd[1]: Started User Runtime Directory /run/user/1000.
Aug 12 15:37:07 rpisurv systemd[1]: Starting User Manager for UID 1000...
Aug 12 15:37:07 rpisurv systemd[546]: Reached target Timers.
Aug 12 15:37:07 rpisurv systemd[546]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Aug 12 15:37:07 rpisurv systemd[546]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Aug 12 15:37:07 rpisurv systemd[546]: Starting D-Bus User Message Bus Socket.
Aug 12 15:37:07 rpisurv systemd[546]: Listening on GnuPG cryptographic agent and passphrase cache.
Aug 12 15:37:07 rpisurv systemd[546]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Aug 12 15:37:07 rpisurv systemd[546]: Reached target Paths.
Aug 12 15:37:07 rpisurv systemd[546]: Listening on GnuPG network certificate management daemon.
Aug 12 15:37:07 rpisurv kernel: [   35.034622] Under-voltage detected! (0x00050005)
Aug 12 15:37:08 rpisurv systemd[546]: Listening on D-Bus User Message Bus Socket.
Aug 12 15:37:08 rpisurv systemd[546]: Reached target Sockets.
Aug 12 15:37:08 rpisurv systemd[546]: Reached target Basic System.
Aug 12 15:37:08 rpisurv systemd[546]: Reached target Default.
Aug 12 15:37:08 rpisurv systemd[1]: Started User Manager for UID 1000.
Aug 12 15:37:08 rpisurv systemd[546]: Startup finished in 468ms.
Aug 12 15:37:08 rpisurv systemd[1]: Started Session 1 of user pi.
Aug 12 15:37:12 rpisurv systemd[1]: systemd-fsckd.service: Succeeded.
Aug 12 15:37:14 rpisurv kernel: [   41.274539] Voltage normalised (0x00000000)
Aug 12 15:37:15 rpisurv systemd[1]: systemd-hostnamed.service: Succeeded.
Aug 12 15:37:17 rpisurv systemd[1]: rpisurv.service: Service RestartSec=20s expired, scheduling restart.
Aug 12 15:37:17 rpisurv systemd[1]: rpisurv.service: Scheduled restart job, restart counter is at 1.
Aug 12 15:37:17 rpisurv systemd[1]: Stopped Rpisurv Raspberry Pi Surveillance.
Aug 12 15:37:17 rpisurv systemd[1]: Started Rpisurv Raspberry Pi Surveillance.
Aug 12 15:37:18 rpisurv rpisurv[578]: pygame 1.9.4.post1
Aug 12 15:37:18 rpisurv rpisurv[578]: Hello from the pygame community. https://www.pygame.org/contribute.html
Aug 12 15:37:18 rpisurv rpisurv[578]: 2021/08/12 15:37:18 - l_default - INFO - Starting rpisurv 3.0.0-beta7
Aug 12 15:37:18 rpisurv rpisurv[578]: 2021/08/12 15:37:18 - l_default - INFO - Auto detected display PHL-Philips_FTV at HDMI 0 with display number 2 1920 x 1080
Aug 12 15:37:18 rpisurv rpisurv[578]: 2021/08/12 15:37:18 - l_default - INFO - Unique id of this installation is 988ab0f34f17a1e68860f49abebad3f43d130fadd78d8d1597a5ba79f90e653a
Aug 12 15:37:21 rpisurv rpisurv[578]: Traceback (most recent call last):
Aug 12 15:37:21 rpisurv rpisurv[578]:   File "surveillance.py", line 188, in <module>
Aug 12 15:37:21 rpisurv rpisurv[578]:     screen_manager=ScreenManager(f'screen_manager_{count}', display, enable_opportunistic_caching_next_screen, disable_pygame)
Aug 12 15:37:21 rpisurv rpisurv[578]:   File "/usr/local/bin/rpisurv/core/ScreenManager.py", line 20, in __init__
Aug 12 15:37:21 rpisurv rpisurv[578]:     self._init_drawinstance()
Aug 12 15:37:21 rpisurv rpisurv[578]:   File "/usr/local/bin/rpisurv/core/ScreenManager.py", line 214, in _init_drawinstance
Aug 12 15:37:21 rpisurv rpisurv[578]:     self.drawinstance = Draw([int(self.display["resolution"]["width"]), int(self.display["resolution"]["height"])], self.disable_pygame, self.name)
Aug 12 15:37:21 rpisurv rpisurv[578]:   File "/usr/local/bin/rpisurv/core/util/draw.py", line 52, in __init__
Aug 12 15:37:21 rpisurv rpisurv[578]:     self.surface = pygame.display.set_mode((self.resolution_width, self.resolution_height))
Aug 12 15:37:21 rpisurv rpisurv[578]: pygame.error: No video mode large enough for 1920x1080
Aug 12 15:37:21 rpisurv systemd[1]: rpisurv.service: Main process exited, code=exited, status=1/FAILURE
Aug 12 15:37:21 rpisurv systemd[1]: rpisurv.service: Failed with result 'exit-code'.

```
error from: cat /usr/local/bin/rpisurv/logs/main.log
```
2021/08/12 15:37:18 - l_default - INFO - Starting rpisurv 3.0.0-beta7
2021/08/12 15:37:18 - l_default - INFO - Auto detected display PHL-Philips_FTV at HDMI 0 with display number 2 1920 x 1080
2021/08/12 15:37:18 - l_default - INFO - Unique id of this installation is 988ab0f34f17a1e68860f49abebad3f43d130fadd78d8d1597a5ba79f90e653a
```

Config files:
Test 1: The default files provided as "showcase"
Test 2: Also tried with my own config with same error and results.

Version 2 works fine:
I am running 2.1.9 without any issues on the exact same hardware but with another SD card without any issues.

Please assist.

**Comment by tubalainen** [comment]
More info here: https://www.tapatalk.com/groups/rpisurv/stuck-at-command-line-after-fresh-installs-t128-s10.html

**Comment by SvenVD** [comment]
merged pull request
