### ISSUE TITLE
cant get it to start on the official pi 7" screen

### ISSUE THREAD

**Issue by zeltak** [SvenVD/rpisurv#131]
Hi all

i have managed to use and start `Rpisurv` on a pi install with an external monitor (via HDMI). on a second install on a new pi with the official  pi 7" screen i cant get it to even start using a super base config with only 1 rasp stream...

this is the error i get

```
pi@raspberrypi:~ $ sudo systemctl status rpisurv
● rpisurv.service - Rpisurv Raspberry Pi Surveillance
   Loaded: loaded (/etc/systemd/system/rpisurv.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2021-08-18 13:55:15 IDT; 6s ago
  Process: 1429 ExecStart=/usr/bin/rpisurv (code=exi
```

the log section:

```
Aug 18 18:26:40 raspberrypi rpisurv[16360]: 2021/08/18 18:26:40 - l_default - INFO - Starting rpisurv 3.0.0-beta7
Aug 18 18:26:40 raspberrypi rpisurv[16360]: [E] No device present
Aug 18 18:26:40 raspberrypi rpisurv[16360]: 2021/08/18 18:26:40 - l_default - ERROR - Could not retrieve devicename for display 2
Aug 18 18:26:40 raspberrypi rpisurv[16360]: 2021/08/18 18:26:40 - l_default - ERROR - Could not autodetect displays, use values from fallback config
Aug 18 18:26:40 raspberrypi rpisurv[16360]: 2021/08/18 18:26:40 - l_default - ERROR - Using config display fallback_device_0 at HDMI 0 with display number 1 800 x 480
Aug 18 18:26:40 raspberrypi rpisurv[16360]: 2021/08/18 18:26:40 - l_default - INFO - Unique id of this installation is c49634958287247ea34ca5cc829d12dd2c80eb4215b480cecc06c87926bd7438
Aug 18 18:26:41 raspberrypi rpisurv[16360]: Traceback (most recent call last):
Aug 18 18:26:41 raspberrypi rpisurv[16360]:   File "surveillance.py", line 188, in <module>
Aug 18 18:26:41 raspberrypi rpisurv[16360]:     screen_manager=ScreenManager(f'screen_manager_{count}', display, enable_opportunistic_caching_next_screen, disable_pygame)
Aug 18 18:26:41 raspberrypi rpisurv[16360]:   File "/usr/local/bin/rpisurv/core/ScreenManager.py", line 20, in __init__
Aug 18 18:26:41 raspberrypi rpisurv[16360]:     self._init_drawinstance()
Aug 18 18:26:41 raspberrypi rpisurv[16360]:   File "/usr/local/bin/rpisurv/core/ScreenManager.py", line 214, in _init_drawinstance
Aug 18 18:26:41 raspberrypi rpisurv[16360]:     self.drawinstance = Draw([int(self.display["resolution"]["width"]), int(self.display["resolution"]["height"])], self.disable_pygame, self.name)
Aug 18 18:26:41 raspberrypi rpisurv[16360]:   File "/usr/local/bin/rpisurv/core/util/draw.py", line 52, in __init__
Aug 18 18:26:41 raspberrypi rpisurv[16360]:     self.surface = pygame.display.set_mode((self.resolution_width, self.resolution_height))
Aug 18 18:26:41 raspberrypi rpisurv[16360]: pygame.error: No video mode large enough for 800x480
Aug 18 18:26:41 raspberrypi systemd[1]: rpisurv.service: Main process exited, code=exited, status=1/FAILURE
Aug 18 18:26:41 raspberrypi systemd[1]: rpisurv.service: Failed with result 'exit-code'.
pi@raspberrypi:~ $
```

any clue what i need to do?

best

Z

**Comment by SvenVD** [comment]
Duplicate https://www.tapatalk.com/groups/rpisurv/cant-get-it-to-start-on-the-official-pi-7-screen-t141.html
