### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pal251** [SvenVD/rpisurv#8]
So I got it installed and I only put in the url for one camera so far.  

I get this error when trying to run it

2016/04/14 05:48:07 - l_default - DEBUG - autodetected resolution of['1824', '984']
2016/04/14 05:48:07 - l_default - DEBUG - nr_of_columns = 2
Traceback (most recent call last):
  File "surveillance.py", line 237, in <module>
    all_camera_streams=setup_camera_streams(rtsp_urls)
  File "surveillance.py", line 185, in setup_camera_streams
    cam_stream=CameraStream(cam_stream_name,rtsp_url)
  File "surveillance.py", line 24, in __init__
    self.port = self.parsed.port
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '<port>'

**Comment by SvenVD** [comment]
Please post the content of /etc/rpisurv here. You're url is probably not correct
